// Code generated by generate-packets.ts. DO NOT EDIT.

package protocol

import "reflect"

type AbilityData struct {
	Points uint16
	Level  uint8
	Id     uint32
}

type ActiveAbility struct {
	Level       uint32
	FeatureType uint16
}

type NpcData struct {
	Unk0_0       *uint8
	Unk1_0       *uint64
	Unk2_0       *uint32
	Struct_375   Array[uint16, Struct_690]
	Unk4_0       *uint32
	Unk5_0       *uint8
	Struct_324   *Array[uint16, [9]byte]
	Unk7_0       *uint8
	Unk8         uint8
	Unk9_0       *uint8
	Unk10        uint8
	Position     Vector3F
	Struct_255   *Array[uint16, [12]byte]
	Unk13_0      *uint32
	Unk14        uint8
	Unk15_0      *uint16
	Unk16        uint8
	Unk17_0      *uint32
	Unk18        uint16
	TypeId       uint32
	DirectionYaw Angle
	StatPair     Array[uint16, struct {
		StatType uint8
		Value    NBytesInt64
	}]
	SpawnIndex        uint32
	Unk23             uint8
	ObjectId          uint64
	StatusEffectDatas Array[uint16, StatusEffectData]
	Unk26_0           *uint16
	Unk27_0           *uint8
	Struct_687        *Struct_687
	TransitIndex      *uint32
	Unk30             uint8
	Unk31_0           *uint8
	Unk32_0           *uint8
}

type PartyMemberData struct {
	ZoneId            uint32
	Unk1              uint8
	Unk2              uint16
	WorldId           uint8
	ClassId           uint16
	Unk5              uint8
	Unk6              uint8
	MaxHp             NBytesInt64
	Position          Vector3F
	Unk9              uint8
	CurHp             NBytesInt64
	Auths             uint8
	Name              string
	TransitIndex      uint32
	CharacterLevel    uint16
	CharacterId       uint64
	PartyMemberNumber uint8
	GearLevel         float32
	Unk18             uint8
	ZoneInstId        uint64
}

type PCStruct struct {
	Unk0              [5]byte
	Unk1              uint8
	Unk2              uint8
	Level             uint16
	Unk4              uint32
	Unk5              uint32
	Unk6              uint16
	Unk5_m            uint32
	StatusEffectDatas Array[uint16, StatusEffectData]
	ClassId           uint16
	Heading           Angle
	Unk11             [25]byte
	Unk12             uint8
	Unk13             uint32
	Unk14             uint16
	Unk15             uint8
	Unk16             uint32
	Unk17             uint8
	Struct_120        Array[uint16, [4]byte]
	Struct_88         ByteArray[uint32]
	Struct_301        Array[uint16, Struct_651]
	Struct_375        Array[uint16, Struct_690]
	Unk22             uint16
	Unk23             uint8
	Unk24             uint32
	Unk25             uint8
	StatPair          Array[uint16, struct {
		StatType uint8
		Value    NBytesInt64
	}]
	Unk27                 uint8
	Unk28                 uint8
	Unk29                 uint8
	Name                  string
	AddonSkillFeatureList Array[uint16, struct {
		SkillId                 uint32
		AddonSkillFeatureIdList Array[uint16, uint32]
	}]
	Unk32       uint8
	Unk33_0     *[12]byte
	PlayerId    uint64
	Unk35       string
	Unk36       uint8
	Unk37       uint32
	GearLevel   float32
	Unk39       uint32
	Struct_302  Array[uint16, Struct_651]
	Unk41       uint64
	CharacterId uint64
	Unk43       uint32
	Unk44       uint32
}

type ProjectileInfo struct {
	Unk0             uint8
	Unk1             uint32
	TargetObjectId   uint64
	Unk3             uint16
	Unk4             uint16
	SkillEffect      uint32
	TripodIndex      TripodIndex
	Unk7             uint8
	TripodLevel      TripodLevel
	Unk9             uint64
	Unk10_0          *uint32
	ProjectileId     uint64
	Struct_324       *Array[uint16, [9]byte]
	OwnerId          uint64
	Unk14            uint32
	ChainSkillEffect uint32
	Unk16            uint64
	SkillLevel       uint8
	SkillId          uint32
	Unk19            uint32
	Unk20_0          *uint64
}

type SkillDamageAbnormalMoveEvent struct {
	Unk8_m              uint16
	Position            Vector3F
	SkillDamageEvent    SkillDamageEvent
	Unk4_m              uint16
	Unk2_m              uint64
	Unk3_m              uint16
	SkillMoveOptionData SkillMoveOptionData
	Unk1_m              uint8
	Destination         Vector3F
}

type SkillDamageEvent struct {
	DamageType uint8
	Modifier   uint8
	Unk3_m     uint16
	MaxHp      NBytesInt64
	DamageAttr *uint8
	CurHp      NBytesInt64
	Damage     NBytesInt64
	TargetId   uint64
}

type StatusEffectData struct {
	OccurTime        LostArkDateTime
	Struct_430       Array[uint16, [7]byte]
	Unk2             uint8
	EffectInstanceId uint32
	StatusEffectId   uint32
	Unk5_0           *uint64
	SkillLevel       uint8
	Value            *struct {
		Data    uint16
		Padding [14]byte
	}
	SourceId  uint64
	TotalTime uint32
	EndTick   uint64
}

type Struct_651 struct {
	Unk0_0          *uint8
	Unk1            uint16
	Unk2            uint16
	Struct_436      Array[uint16, [14]byte]
	LostArkDateTime LostArkDateTime
	Unk5            uint32
}

type Struct_687 struct {
	LostArkString string
	Unk1          uint8
	Unk2          uint8
	Unk3          uint16
	Unk4          uint64
	Struct_302    Array[uint16, Struct_651]
	Struct_88     ByteArray[uint32]
	Unk7          uint8
}

type Struct_690 struct {
	Unk0 uint8
	Unk1 NBytesInt64
	Unk2 NBytesInt64
	Unk3 uint8
	Unk4 uint8
	Unk5 uint64
	Unk6 uint16
}

type Struct_707 struct {
	Unk0_0 *[9]byte
	Unk1_0 *uint32
	Unk2   uint32
	Unk3   uint32
	Unk4   uint32
}

type TrackMoveInfo struct {
	Unk0   [12]byte
	Unk1_0 *[12]byte
	Unk2   uint32
	Unk3   uint32
}

type UnpublishObject struct {
	UnpublishReason uint8
	ObjectId        uint64
}

type ZoneStatusEffectData struct {
	StackCount uint8
	Id         uint32
	InstanceId uint64
	Target     uint8
}

type PKTAbilityChangeNotify struct {
	AbilityDataList Array[uint16, AbilityData]
}

type PKTActiveAbilityNotify struct {
	ActiveAbilityList Array[uint16, ActiveAbility]
	ObjectId          uint64
}

type PKTAddonSkillFeatureChangeNotify struct {
	Struct_120            Array[uint16, [4]byte]
	AddonSkillFeatureList Array[uint16, struct {
		SkillId                 uint32
		AddonSkillFeatureIdList Array[uint16, uint32]
	}]
	ObjectId uint64
}

type PKTAuthTokenResult struct {
	Unk1_m           ByteArray[uint32]
	PacketResultCode uint32
}

type PKTBlockSkillStateNotify struct {
	Padding0             [2]byte
	ParalyzationMaxPoint uint32
	Padding1             [1]byte
	Type                 uint8
	ObjectId             uint64
	ParalyzationPoint    uint32
}

type PKTCounterAttackNotify struct {
	Padding0 [1]byte
	SourceId uint64
	TargetId uint64
	Padding1 [1]byte
	Type     uint32
	Padding2 [1]byte
}

type PKTDeathNotify struct {
	Unk0     uint8
	Unk1_0   *uint8
	Unk2     uint32
	Unk3_0   *uint8
	Unk4     uint16
	Unk5_0   *uint8
	SourceId uint64
	Unk7     uint32
	TargetId uint64
	Unk9     uint64
}

type PKTIdentityGaugeChangeNotify struct {
	Padding0       [1]byte
	PlayerId       uint64
	IdentityGauge1 uint32
	IdentityGauge2 uint32
	IdentityGauge3 uint32
	Padding1       [2]byte
}

type PKTInitAbility struct {
	AbilityDataList Array[uint16, AbilityData]
	Struct_125      Array[uint16, [48]byte]
}

type PKTInitEnv struct {
	Unk0            uint64
	Unk1            uint8
	Unk2            uint32
	PlayerId        uint64
	Unk4            uint32
	Struct_557      string
	LostArkDateTime LostArkDateTime
	Struct_27       Array[uint16, struct {
		Struct_543    string
		Struct_557    string
		VersionString string
	}]
}

type PKTInitLocal struct {
	Unk0       uint32
	Unk1       uint8
	Struct_215 Array[uint16, [17]byte]
	Unk3       uint64
	StatPair   Array[uint16, struct {
		StatType uint8
		Value    NBytesInt64
	}]
	AddonSkillFeatureList Array[uint16, struct {
		SkillId                 uint32
		AddonSkillFeatureIdList Array[uint16, uint32]
	}]
	Unk6              uint8
	Struct_125        Array[uint16, [48]byte]
	AbilityDataList   Array[uint16, AbilityData]
	Struct_120        Array[uint16, [4]byte]
	Struct_328        Array[uint16, [30]byte]
	StatusEffectDatas Array[uint16, StatusEffectData]
	Struct_408        Array[uint16, Struct_707]
	Unk13             uint8
	Unk14_0           *uint32
	Unk15             uint64
}

type PKTInitPC struct {
	ClassId  uint16
	Unk1     uint8
	Unk2     uint8
	Unk3     uint32
	Unk4     uint8
	Unk5     uint8
	Unk6     uint32
	Unk7     uint8
	Unk8     uint8
	Unk9     uint8
	Unk10    [35]byte
	Unk11    uint8
	Unk12    uint64
	Unk13    uint32
	StatPair Array[uint16, struct {
		StatType uint8
		Value    NBytesInt64
	}]
	Unk15             [25]byte
	Struct_328        Array[uint16, [30]byte]
	Unk17             uint32
	Unk18             uint16
	Struct_323        string
	Unk20             uint32
	Unk21             uint32
	Unk22             uint32
	Unk23             uint8
	CharacterId       uint64
	Unk25             uint8
	Struct_215        Array[uint16, [17]byte]
	Unk27             uint64
	Unk28             uint16
	Unk29             uint8
	Unk30             uint16
	Unk31             uint8
	Unk32             uint16
	Struct_96         ByteArray[uint16]
	Unk34             uint8
	Struct_375        Array[uint16, Struct_690]
	Unk36_0           *uint32
	Unk37             uint32
	Unk38             uint64
	Unk39             uint32
	Unk40             uint8
	Unk41             uint8
	Level             uint16
	Unk43             uint32
	Unk44             uint8
	PlayerId          uint64
	Unk46             uint32
	Unk47             uint8
	Unk48             uint8
	Unk49             uint8
	GearLevel         float32
	Unk51             [120]byte
	Name              string
	StatusEffectDatas Array[uint16, StatusEffectData]
	Unk54             uint64
	Unk55             uint8
	Unk56             uint32
}

type PKTMigrationExecute struct {
	Account_CharacterId1 uint64
	ServerAddr           string
	Account_CharacterId2 uint64
	Unk3                 uint32
}

type PKTNewNpc struct {
	Unk0_0_0 *uint64
	Unk1     uint8
	Unk0_0   *struct {
		Unk0_0 string
		Unk0_1 string
	}
	Unk3_0    *uint8
	NpcStruct NpcData
}

type PKTNewNpcSummon struct {
	NpcData       NpcData
	PublishReason uint8
	OwnerId       uint64
	Padding0      [31]byte
}

type PKTNewPC struct {
	Unk5_0_m      *[20]byte
	Unk3_0_m      *uint32
	PCStruct      PCStruct
	Unk0_m        uint8
	TrackMoveInfo *TrackMoveInfo
	Unk2_m        uint8
	Unk4_0_m      *[12]byte
}

type PKTNewProjectile struct {
	ProjectileInfo ProjectileInfo
}

type PKTParalyzationStateNotify struct {
	ObjectId             uint64
	NoHitCheckTime       uint32
	ParalyzationMaxPoint uint32
	ParalyzationPoint    uint32
	HitCheckTime         uint32
	Enable               bool
	Padding0             [1]byte
	DecreasePoint        uint32
	Padding1             [1]byte
}

type PKTPartyInfo struct {
	RaidInstanceId  uint32
	LootGrade       uint32
	PartyLootType   uint8
	PartyInstanceId uint32
	MemberDatas     Array[uint16, PartyMemberData]
	PartyType       uint8
}

type PKTPartyLeaveResult struct {
	PartyInstanceId uint32
	Name            string
	PartyLeaveType  uint8
}

type PKTPartyPassiveStatusEffectAddNotify struct {
	PassiveStatusEffectList Array[uint16, uint32]
	ObjectId                uint64
	Unk0_m                  uint8
}

type PKTPartyPassiveStatusEffectRemoveNotify struct {
	PassiveStatusEffectList Array[uint16, uint32]
	ObjectId                uint64
}

type PKTPartyStatusEffectAddNotify struct {
	StatusEffectDatas Array[uint16, StatusEffectData]
	PlayerIdOnRefresh uint64
	CharacterId       uint64
	Unk3              uint8
	Unk4              uint64
}

type PKTPartyStatusEffectRemoveNotify struct {
	StatusEffectIds Array[uint16, uint32]
	CharacterId     uint64
	Unk2            uint64
	Reason          uint8
}

type PKTPartyStatusEffectResultNotify struct {
	Padding0        [1]byte
	CharacterId     uint64
	Padding1        [4]byte
	RaidInstanceId  uint32
	PartyInstanceId uint32
	Padding2        [22]byte
}

type PKTPassiveStatusEffectAddNotify struct {
	PassiveStatusEffectList Array[uint16, uint32]
}

type PKTPassiveStatusEffectRemoveNotify struct {
	PassiveStatusEffectList Array[uint16, uint32]
}

type PKTRaidBossKillNotify struct {
	Unk0 [5]byte
}

type PKTRaidResult struct {
	Unk0      uint64
	Unk1      uint64
	Unk2      uint8
	Unk3      uint8
	Unk4      uint64
	Unk5      uint8
	Struct_47 Array[uint16, struct {
		Struct_506 ByteArray[uint16]
		Unk0_0_1   NBytesInt64
		Unk0_0_2   NBytesInt64
		Unk0_0_3   uint32
	}]
	Unk7 uint64
}

type PKTRemoveObject struct {
	UnpublishedObjects Array[uint16, UnpublishObject]
}

type PKTSkillDamageAbnormalMoveNotify struct {
	SkillEffectId                 uint32
	SkillDamageAbnormalMoveEvents Array[uint16, SkillDamageAbnormalMoveEvent]
	Unk1_m                        uint8
	Unk2_m                        uint32
	SkillId                       uint32
	SourceId                      uint64
}

type PKTSkillDamageNotify struct {
	SkillLevel        uint8
	SourceId          uint64
	SkillEffectId     uint32
	SkillDamageEvents Array[uint16, SkillDamageEvent]
	SkillId           uint32
}

type PKTSkillStageNotify struct {
	SkillId  uint32
	Padding0 [16]byte
	SourceId uint64
	Padding1 [19]byte
	Stage    uint8
	Padding2 [5]byte
}

type PKTSkillStartNotify struct {
	SkillId           uint32
	NewPosition       Vector3F
	CurDirectionYaw   Angle
	Unk1_m            *uint32
	SkillLevel        uint8
	PitchRotation     *Angle
	SkillOptionData   SkillOptionData
	NewDirectionYaw   Angle
	SourceId          uint64
	AiStateId         *uint32
	AimTargetPosition Vector3F
	CurPosition       Vector3F
}

type PKTStatChangeOriginNotify struct {
	ObjectId            uint64
	Unk1                uint8
	Unk2_0              *uint32
	StatPairChangedList Array[uint16, struct {
		StatType uint8
		Value    NBytesInt64
	}]
	Unk4 Array[uint16, struct {
		StatType uint8
		Value    NBytesInt64
	}]
}

type PKTStatusEffectAddNotify struct {
	New              bool
	Unk1             uint64
	Unk2_0           *uint64
	ObjectId         uint64
	StatusEffectData StatusEffectData
}

type PKTStatusEffectDurationNotify struct {
	Padding0         [1]byte
	TargetId         uint64
	Padding1         [1]byte
	ExpirationTick   uint64
	Padding2         [1]byte
	EffectInstanceId uint32
}

type PKTStatusEffectRemoveNotify struct {
	Reason          uint8
	StatusEffectIds Array[uint16, uint32]
	ObjectId        uint64
}

type PKTStatusEffectSyncDataNotify struct {
	ObjectId         uint64
	Value            uint32
	Padding0         [6]byte
	EffectInstanceId uint32
	CharacterId      uint64
}

type PKTTriggerBossBattleStatus struct {
	TriggerId uint32
	Unk2_m    bool
	Padding0  [1]byte
	Step      uint32
}

type PKTTriggerFinishNotify struct {
	PacketResultCode uint32
	Unk0_m           uint32
	InvolvedPCs      Array[uint16, uint64]
	TriggerId        uint32
}

type PKTTriggerStartNotify struct {
	TriggerSignalType uint32
	TriggerId         uint32
	SourceId          uint64
	InvolvedPCs       Array[uint16, uint64]
}

type PKTTroopMemberUpdateMinNotify struct {
	Position          uint64
	MaxHp             NBytesInt64
	StatusEffectDatas Array[uint16, StatusEffectData]
	Unk0_m            uint32
	CurHp             NBytesInt64
	CharacterId       uint64
}

type PKTZoneObjectUnpublishNotify struct {
	ObjectId uint64
	Padding0 [2]byte
}

type PKTZoneStatusEffectAddNotify struct {
	ZoneStatusEffectDataList Array[uint16, ZoneStatusEffectData]
}

type PKTZoneStatusEffectRemoveNotify struct {
	Padding0       [2]byte
	StatusEffectId uint32
}

func init() {

	OpCodeToPacket[1400] = reflect.TypeOf(PKTAbilityChangeNotify{})
	OpCodeToPacket[46763] = reflect.TypeOf(PKTActiveAbilityNotify{})
	OpCodeToPacket[15935] = reflect.TypeOf(PKTAddonSkillFeatureChangeNotify{})
	OpCodeToPacket[51838] = reflect.TypeOf(PKTAuthTokenResult{})
	OpCodeToPacket[24956] = reflect.TypeOf(PKTBlockSkillStateNotify{})
	OpCodeToPacket[20022] = reflect.TypeOf(PKTCounterAttackNotify{})
	OpCodeToPacket[55094] = reflect.TypeOf(PKTDeathNotify{})
	OpCodeToPacket[53656] = reflect.TypeOf(PKTIdentityGaugeChangeNotify{})
	OpCodeToPacket[1278] = reflect.TypeOf(PKTInitAbility{})
	OpCodeToPacket[29922] = reflect.TypeOf(PKTInitEnv{})
	OpCodeToPacket[47316] = reflect.TypeOf(PKTInitLocal{})
	OpCodeToPacket[36886] = reflect.TypeOf(PKTInitPC{})
	OpCodeToPacket[32608] = reflect.TypeOf(PKTMigrationExecute{})
	OpCodeToPacket[34376] = reflect.TypeOf(PKTNewNpc{})
	OpCodeToPacket[58650] = reflect.TypeOf(PKTNewNpcSummon{})
	OpCodeToPacket[38230] = reflect.TypeOf(PKTNewPC{})
	OpCodeToPacket[48846] = reflect.TypeOf(PKTNewProjectile{})
	OpCodeToPacket[13954] = reflect.TypeOf(PKTParalyzationStateNotify{})
	OpCodeToPacket[2273] = reflect.TypeOf(PKTPartyInfo{})
	OpCodeToPacket[57280] = reflect.TypeOf(PKTPartyLeaveResult{})
	OpCodeToPacket[44797] = reflect.TypeOf(PKTPartyPassiveStatusEffectAddNotify{})
	OpCodeToPacket[48015] = reflect.TypeOf(PKTPartyPassiveStatusEffectRemoveNotify{})
	OpCodeToPacket[56075] = reflect.TypeOf(PKTPartyStatusEffectAddNotify{})
	OpCodeToPacket[9020] = reflect.TypeOf(PKTPartyStatusEffectRemoveNotify{})
	OpCodeToPacket[46121] = reflect.TypeOf(PKTPartyStatusEffectResultNotify{})
	OpCodeToPacket[8484] = reflect.TypeOf(PKTPassiveStatusEffectAddNotify{})
	OpCodeToPacket[48556] = reflect.TypeOf(PKTPassiveStatusEffectRemoveNotify{})
	OpCodeToPacket[45163] = reflect.TypeOf(PKTRaidBossKillNotify{})
	OpCodeToPacket[34118] = reflect.TypeOf(PKTRaidResult{})
	OpCodeToPacket[42767] = reflect.TypeOf(PKTRemoveObject{})
	OpCodeToPacket[59998] = reflect.TypeOf(PKTSkillDamageAbnormalMoveNotify{})
	OpCodeToPacket[26332] = reflect.TypeOf(PKTSkillDamageNotify{})
	OpCodeToPacket[9713] = reflect.TypeOf(PKTSkillStageNotify{})
	OpCodeToPacket[52727] = reflect.TypeOf(PKTSkillStartNotify{})
	OpCodeToPacket[8370] = reflect.TypeOf(PKTStatChangeOriginNotify{})
	OpCodeToPacket[29231] = reflect.TypeOf(PKTStatusEffectAddNotify{})
	OpCodeToPacket[43493] = reflect.TypeOf(PKTStatusEffectDurationNotify{})
	OpCodeToPacket[36929] = reflect.TypeOf(PKTStatusEffectRemoveNotify{})
	OpCodeToPacket[39153] = reflect.TypeOf(PKTStatusEffectSyncDataNotify{})
	OpCodeToPacket[23399] = reflect.TypeOf(PKTTriggerBossBattleStatus{})
	OpCodeToPacket[48546] = reflect.TypeOf(PKTTriggerFinishNotify{})
	OpCodeToPacket[54667] = reflect.TypeOf(PKTTriggerStartNotify{})
	OpCodeToPacket[51633] = reflect.TypeOf(PKTTroopMemberUpdateMinNotify{})
	OpCodeToPacket[37146] = reflect.TypeOf(PKTZoneObjectUnpublishNotify{})
	OpCodeToPacket[44701] = reflect.TypeOf(PKTZoneStatusEffectAddNotify{})
	OpCodeToPacket[4905] = reflect.TypeOf(PKTZoneStatusEffectRemoveNotify{})

}
