name: "Build Windows Release"

on:
  workflow_dispatch:
  pull_request:
  create:

permissions:
  contents: write
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20.2"
      - uses: denoland/setup-deno@v1
      - uses: extractions/setup-just@v1
      - uses: actions/setup-node@v3
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build
        run: deno run --allow-all bin/build-release.ts ${{ github.ref }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            shandi.exe
            *.exe.patch
          draft: true
